Supply/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('business.urls')),
    path('chat/',include('chat.urls'))
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views
from accounts.views import SupplierSignupView,CustomerSignupView
app_name="accounts"
urlpatterns=[
path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
path('logout/',auth_views.LogoutView.as_view(template_name='accounts/logout.html'),name="logout"),
path('supplier/',SupplierSignupView.as_view(),name="supplier"),
path('customer/',CustomerSignupView.as_view(),name="customer"),
path('SupplierProfile/',views.SupplierProfileView,name="profile"),
path('CustomerProfile/',views.CustomerProfileView,name="profilecus"),
]

business/urls.py
from django.urls import path
from business import views
app_name="business"

urlpatterns=[
path('',views.WelcomeView,name="welcome"),
path('home/',views.HomeView,name='home'),
path('product/<id>/details/',views.ProductView,name="details"),
path('update/product/<id>/',views.UpdateView,name='update'),
path('delete/product/<id>/',views.ProductDelete,name='delete'),
path('addProduct/',views.AddProductView,name="addProduct"),
path('supplier/<id>/details/',views.SupplierDetailsView,name="supplierdetails"),
path('counties/',views.CountyView,name='county'),
path('supply/',views.SupplierData,name="supply"),
path('supplier/details/<id>/',views.SpecificSupplier,name="supplierlocation")
]

chat/urls.py
from django.urls import path
from chat import views
from django.contrib.auth import views as auth_views
app_name="chat"


urlpatterns=[
path('',views.index,name='index'),
path('<room_name>/',views.room,name="room"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager,AbstractBaseUser
from django.contrib.gis.db import models



class custommanager(BaseUserManager):
    def create_user(self,email,username,password=None,is_active=True,is_staff=False,is_admin=False,is_supplier=False,is_customer=False):
        if not email:
            raise ValueError('Users must have an email.')
        if not password:
            raise ValueError('Users must have a password.')
        if not username:
            raise ValueError('Users must have a username.')
        user_obj=self.model(
        email=self.normalize_email(email),
        username=username
        )
        user_obj.set_password(password)
        user_obj.is_active=is_active
        user_obj.is_admin=is_admin
        user_obj.is_staff=is_staff
        user_obj.is_customer=is_customer
        user_obj.is_supplier=is_supplier
        user_obj.save(using=self._db)

        return user_obj
    def create_staff(self,email,username,password=None):
        user=self.create_user(
        email,
        username,
        password=password,
        is_staff=True,
        is_supplier=False,
        is_customer=False,
        is_active=True
        )
        return user
    def create_superuser(self,email,username,password=None):
        user=self.create_user(
        email,
        username,
        password=password,
        is_staff=True,
        is_admin=True,
        is_supplier=True,
        is_customer=True,
        is_active=True
        )
        return user
class User(AbstractBaseUser):
    username=models.CharField(max_length=255,verbose_name="Username",unique=True)
    first_name=models.CharField(max_length=256,blank=True,null=True)
    last_name=models.CharField(max_length=256,blank=True,null=True)
    email=models.EmailField(verbose_name='Email Address',max_length=255,unique=True)
    is_active=models.BooleanField(default=True)
    is_admin=models.BooleanField(default=False)
    is_staff=models.BooleanField(default=False)
    is_supplier=models.BooleanField(default=False)
    is_customer=models.BooleanField(default=False)

    USERNAME_FIELD='email'
    REQUIRED_FIELDS=['username']
    objects=custommanager()

    def __str__(self):
        return self.username
    def has_perm(self,perm,obj=None):
        return True
    def has_module_perms(self,app_label):
        return True
    @property
    def staff(self):
        return self.staff
    @property
    def admin(self):
        return self.admin
    @property
    def active(self):
        return self.active
    @property
    def supplier(self):
        return self.supplier
    @property
    def customer(self):
        return self.customer
class Categories(models.Model):
    category_choices=(
    ('Beauty & Cosmetics','Beauty & Cosmetics'),
    ('Electronics','Electronics')
    )
    category=models.CharField(max_length=30,choices=category_choices,unique=True)
    def __str__(self):
        return self.category
    class Meta:
        verbose_name_plural="Categories"
class Customer(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    interest=models.ManyToManyField(Categories)
    image=models.ImageField(upload_to='Suppliers-profile',default="default.jpg")
    status=models.TextField(blank=True,null=True)
    def __str__(self):
        return self.user.username

class Supplier(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    location=models.PointField(srid=4326,blank=True,null=True)
    image=models.ImageField(upload_to='customer-profile',default="default.jpg")
    telephone=models.CharField(max_length=20,default="+254")
    status=models.TextField(blank=True,null=True)

    def __str__(self):
        return self.user.username
#===========================================================================
class Counties(models.Model):
    fid = models.FloatField()
    objectid = models.FloatField()
    code_id = models.FloatField()
    name = models.CharField(max_length=70)
    code = models.CharField(max_length=3)
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    area = models.FloatField()
    geom = models.MultiPolygonField(srid=4326)

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.db import transaction
from accounts.models import User,Supplier,Customer,Categories
from django.contrib.gis import forms



class UserCreationForm(ModelForm):
    class Meta:
        model=User
        fields=('username','first_name','last_name','email')
    password1=forms.CharField(label='Password',widget=forms.PasswordInput)
    password2=forms.CharField(label='Password Confirmation',widget=forms.PasswordInput)
    def cleaned_password2(self):
        password1=self.cleaned_data.get('password1')
        password2=self.cleaned_data.get('password2')
        if password1 and password2 and password1!=password2:
            raise forms.ValidationError('Password don\'t match.')
        return password2
    def save(self,commit=False):
        user=super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

class UserChangeForm(ModelForm):
    password=ReadOnlyPasswordHashField()
    class Meta:
        model=User
        fields=('username','first_name','last_name','is_admin','is_staff','is_active','is_supplier','is_customer')
    def cleaned_password(self):
        return self.initial['password']
class SupplierSignupForm(ModelForm):
    '''agreement=forms.ModelMultipleChoiceField(
    queryset=Agreement.objects.all(),
    widget=forms.CheckboxSelectMultiple,
    required=True
    )'''
    class Meta(ModelForm):
        model=User
        fields=('username','first_name','last_name','email')
    password1=forms.CharField(label='Password',widget=forms.PasswordInput)
    password2=forms.CharField(label='Password Confirmation',widget=forms.PasswordInput)
    def clean_password2(self):
        password1=self.cleaned_data.get('password1')
        password2=self.cleaned_data.get('password2')
        if password1 and password2 and password1!=password2:
            raise forms.ValidationError("Password don\'t match")

        return password2
    @transaction.atomic
    def save(self,commit=True):
        user=super().save(commit=False)
        user.is_supplier=True
        user.is_admin=False
        user.is_staff=False
        user.is_active=True
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        supplier=Supplier.objects.create(user=user)
        return user

class CustomerSignupForm(ModelForm):
        class Meta(ModelForm):
            model=User
            fields=('username','first_name','last_name','email')
        password1=forms.CharField(label='Password',widget=forms.PasswordInput)
        password2=forms.CharField(label='Password Confirmation',widget=forms.PasswordInput)
        def clean_password2(self):
            password1=self.cleaned_data.get('password1')
            password2=self.cleaned_data.get('password2')
            if password1 and password2 and password1!=password2:
                raise forms.ValidationError("Password don\'t match")

            return password2
        interest=forms.ModelMultipleChoiceField(
            queryset=Categories.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=True
            )
        @transaction.atomic
        def save(self,commit=True):
            user=super().save(commit=False)
            user.is_active=True
            user.is_customer=True
            user.is_admin=False
            user.is_staff=False
            user.set_password(self.cleaned_data['password1'])
            if commit:
                user.save()
            customer=Customer.objects.create(user=user)
            customer.interest.add(*self.cleaned_data.get('interest'))
            return user
from leaflet.forms.widgets import LeafletWidget
class SupplierProfileUpdateForm(ModelForm):
    #location=forms.PointField()
    class Meta:
        model=Supplier
        fields=['location','telephone','status','image']
        widgets={'location':LeafletWidget()}
class SupplierUserUpdateForm(ModelForm):
    username=forms.CharField(label="Business Name",max_length=50)
    class Meta:
        model=User
        fields=['username','first_name','last_name']
class CustomerProfileUpdateForm(ModelForm):
    interest=forms.ModelMultipleChoiceField(
    queryset=Categories.objects.all(),
    widget=forms.CheckboxSelectMultiple,
    required=True
    )
    class Meta:
        model=Customer
        fields=['interest','image','status']
class CustomerUserUpdateForm(ModelForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name']

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.views.generic import CreateView
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from accounts.forms import CustomerSignupForm,SupplierSignupForm,SupplierUserUpdateForm,SupplierProfileUpdateForm,CustomerUserUpdateForm,CustomerProfileUpdateForm
from accounts.models import User,Supplier,Customer
from accounts.decorators import supplier_required,customer_required


class SupplierSignupView(CreateView):
    model=User
    form_class=SupplierSignupForm
    template_name='accounts/supplierSignup.html'
    def get_context_data(self,**kwargs):
        kwargs['user_type']='supplier'
        return super().get_context_data(**kwargs)
    def form_valid(self,form):
        if form.is_valid:
            user=form.save()
            login(self.request,user)
            return HttpResponseRedirect('/accounts/login/')
class CustomerSignupView(CreateView):
    model=User
    form_class=CustomerSignupForm
    template_name='accounts/customerSignup.html'
    def get_context_data(self,**kwargs):
        kwargs['user_type']='customer'
        return super().get_context_data(**kwargs)
    def form_valid(self,form):
        if form.is_valid():
            user=form.save()
            login(self.request,user)
            return HttpResponseRedirect('/accounts/login/')
#==========================Profile======================================================
@login_required
@supplier_required
def SupplierProfileView(request):
    supProfile=Supplier.objects.get(user=request.user)
    user_form=SupplierUserUpdateForm(instance=request.user)
    form=SupplierProfileUpdateForm(instance=supProfile)
    if request.method=="POST":
        form=SupplierProfileUpdateForm(request.POST or None,request.FILES or None,instance=supProfile)
        user_form=SupplierUserUpdateForm(request.POST or None,request.FILES or None,instance=request.user)
        if form.is_valid() and user_form.is_valid():
            form.save()
            user_form.save()
    context={
    'supProfile':supProfile,
    'form':form,
    'user_form':user_form
    }
    return render(request,'accounts/SupplierProfile.html',context)
@login_required
@customer_required
def CustomerProfileView(request):
    custProfile=Customer.objects.get(user=request.user)
    form=CustomerProfileUpdateForm(instance=custProfile)
    user_form=CustomerUserUpdateForm(instance=request.user)
    if request.method=="POST":
        form=CustomerProfileUpdateForm(request.POST or None,request.FILES or None,instance=custProfile)
        user_form=CustomerUserUpdateForm(request.POST or None,request.FILES or None,instance=request.user)
        if form.is_valid() and user_form.is_valid():
            form.save()
            user_form.save()
    context={
    'custProfile':custProfile,
    'form':form,
    'user_form':user_form
    }
    return render(request,'accounts/CustomerProfile.html',context)

accounts/templates/accounts/CustomerProfile.html
{%extends 'accounts/base.html'%}
{%load crispy_forms_tags%}
{%load leaflet_tags%}
{%leaflet_js%}
{%leaflet_css%}
{%block content%}
<div class="container">
  <div class="col-sm-10">
  <div class="card shadow-lg" style=background-color:#ffffff;>
    <div class="card-header text-white" style=background-color:#6d1af5;>
      <legend>My Profile.</legend>
      </div>
      <div class="card-body m-1">
        <div class="row">
          <div class="col-sm-2">
  <img class="rounded-circle" height="100" width="100" src="{{custProfile.image.url}}" alt="edit">
</div>
<div class="col-sm-6">
<b>Userame:</b> {{user.username}}<br>
<b>Name:</b> {{user.first_name}} {{user.last_name}}<br>
<b>Email:</b> {{user.email}}<br>
{%if custProfile.status%}
<b>Status: </b>{{custProfile.status}}<br>
{%endif%}
</div>
<div class="col-sm-4">
  <div class="card">
  <div class="card-header text-white" style=background-color:#1b70df;>
    <h6>Interests</h6>
    </div>
    <div class="card-body">
  {%for cust in custProfile.interest.all%}
{{forloop.counter}}. {{cust.category}}
<br>
{%endfor%}

{%leaflet_map "gis"%}
</div>
  </div>
  </div>
</div>
</div>
<div class="col-sm-10">
<div class="card border-white m-1" style=background-color:transparent;>
  <div class="card-header text-white" style=background-color:#6e9e2e;>
<legend>Update Profile.</legend>
    </div>
    <div class="card-body">
<form method="POST" action="" enctype="multipart/form-data">
{%csrf_token%}
{{user_form|crispy}}
{{form|crispy}}
<div class="update" align=center>
<button class="btn text-white col-sm-5" style=background-color:#e60023;>Update Profile</button>
</div>
  </form>
  </div>
  </div>
  </div>
  </div>
  </div>
  </div>
{%endblock%}

accounts/templates/accounts/SupplierProfile.html
{%extends 'accounts/base.html'%}
{%load crispy_forms_tags%}
{%load leaflet_tags%}

{%block content%}
{%leaflet_js plugins="forms"%}
{%leaflet_css plugins="forms"%}
<div class="container">
  <div class="col-sm-10">
  <div class="card" align=left>
    <div class="card-header text-white" style=background-color:forestgreen;>
      <legend>My Profile.</legend>
      </div>
      <div class="card-body m-2">
        <div class="row">
          <div class="col-sm-3">
  <img class="rounded-circle" width='100' height='100' src="{{supProfile.image.url}}" alt="edit">
  </div>
  <div class="col-sm-9">
<b>Business Name:</b> {{user.username}}<br>
<b>Owner's Name:</b> {{user.first_name}} {{user.last_name}}<br>
<b>Email Address:</b> {{user.email}}<br>
<b>Phone Number:</b> {{supProfile.telephone}}<br>
<b>Status:</b> {{supProfile.status}}
</div>
</div>
<div class="col-sm-10">
<div class="card border-white ">
<div class="card-header text-white" style=background-color:dodgerblue;>
<legend>Update Profile.</legend>
  </div>
  <div class="card-body">
<form method="POST" action="" enctype="multipart/form-data">
{%csrf_token%}
{{user_form|crispy}}
{{form|crispy}}
<br>
<div class="map p-1">
  maps
</div>
<button class="btn btn-info">Update Profile</button>
  </form>
  </div>
  </div>
</div>
</div>
</div>
</div>
  </div>
{%endblock%}

accounts/templates/accounts/base.html
{%load icons%}
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}" />

  <script src="{% static 'main.js' %}"></script>
    <title>Day Codes!</title>

    <nav class="navbar navbar-expand-lg navbar-dark sticky-top" style=background-color:#293352;>
      <div class="container-fluid ">
      <a class="navbar-brand" href="#">DayCodes</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myToggle"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="myToggle">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            {%if user.is_authenticated%}
            <a class="nav-link" href="{%url 'business:home'%}">Home
            </a>
            {%else%}
            <a class="nav-link" href="{%url 'business:welcome'%}">Home</a>
            {%endif%}
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#">Contact</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#">About</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          {%if user.is_authenticated%}
   <li class="nav-item">
     <a class="nav-link text-white">1
       <i class="fa fa-envelope fa-lg" style=color:lavender;></i>
     </a>
   </li>
   <li class="nav-item dropdown">
     <a class="nav-link" id="RightDropDownMenu" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">
       <i class="fa fa-user-circle-o fa-lg" style=color:lavender; aria-hidden="true"></i>
     </a>
     <div class="dropdown-menu dropdown-menu-lg-right text-white"
       aria-labelledby="RightDropDownMenu" style=background-color:pink;>
       {%if user.is_supplier and user.is_authenticated%}
       <a class="dropdown-item" href="{%url 'accounts:profile'%}">Profile</a>
       <a class="dropdown-item" href="{%url 'accounts:logout'%}">Logout</a>
       {%elif user.is_customer and user.is_authenticated %}
       <a class="dropdown-item" href="{%url 'accounts:profilecus'%}">Profile</a>
       <a class="dropdown-item" href="#">DashBoard</a>
       <a class="dropdown-item" href="{%url 'accounts:logout'%}">Logout</a>
       {%else%}
       <a class="dropdown-item" href="{%url 'accounts:login'%}">Login</a>
         {%endif%}
     </div>
   </li>
   {%else%}
   <li class="nav-item dropdown">
     <a class="nav-link" id="RightDropDownMenu" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">
         <i class="fa fa-user-circle-o fa-lg" style=color:lavender;></i>
     </a>
     <div class="dropdown-menu dropdown-menu-lg-right text-white" style=background-color:pink; aria-labelledby='SignupDropdown'>
       <a class="dropdown-item" href="{%url 'accounts:login'%}">Login</a>
       <a class="dropdown-item" href="{%url 'accounts:customer'%}">Customer Signup</a>
       <a class="dropdown-item" href="{%url 'accounts:supplier'%}">Supplier Signup</a>

     </div>
   </li>
   {%endif%}
 </ul>
        <form class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          </div>
        </form>
      </div>
    </div>
    </nav>



  </head>
  <body>
    <div class="mycontent m-2">
    {%block content%}

    {%endblock%}
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

accounts/templates/accounts/customerSignup.html
{%extends 'accounts/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="container">
    <div class="card text-white shadow-lg" style=background-color:#44505e;>
      <div class="card-header text-white" style=background-color:dodgerblue;>
        <legend>Create A Free Customer Account.</legend>
        </div>
        <div class="card-body">
<form method="POST" action="">
  <div class="row">
  <div class="col-sm-6">
{%csrf_token%}
{{form.username|as_crispy_field}}
{{form.first_name|as_crispy_field}}
{{form.last_name|as_crispy_field}}
{{form.email|as_crispy_field}}
{{form.password1|as_crispy_field}}
{{form.password2|as_crispy_field}}
</div>
<div class="col-sm-6">
  {{form.interest|as_crispy_field}}
  </div>
</div>
<div class="signbutton" align=center>
<button class="btn btn-primary text-white col-sm-4">Sign Up</button>
</div>
  </form>
  </div>
  </div>
  </div>
  </div>
{%endblock%}

accounts/templates/accounts/login.html
{%extends 'accounts/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="container p-1">
  <div class="jum" align=center>
    <div class="col-10 col-sm-5" align=left>
  <div class="card shadow-lg text-white" style=background-color:#44505e;>
    <div class="card-header text-white" style=background-color:dodgerblue;>
<legend>Welcome Back,</legend>
<h6>sign in to continue</h6>
</div>
<div class="card-body">
<form method="POST" action="">
{%csrf_token%}
{{form|crispy}}
<div class="btton" align=center>
  <div class="forgot m-1" align=left>
  <a href=""><small>Forgot Password?</small></a>
  </div>
<button class="btn shadow btn-primary col-sm-12">Sign In</button><br>
<small class="text-muted m-1">Don't have an account?</small><br>
</div>
  </form>
  <a href="{%url 'accounts:customer'%}"><button class="btn btn-primary col-sm-12">Create Account</button></a>
  </div>
  </div>
  </div>
  </div>
  </div>
{%endblock%}

accounts/templates/accounts/logout.html
{%extends 'accounts/base.html'%}
{%block content%}
<h1>You have successfully been logged out </h1>

{%endblock%}

accounts/templates/accounts/supplierSignup.html
{%extends 'accounts/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="container">
  <div class="col-sm-12">
    <div class="card text-white shadow-lg" style=background-color:#44505e;>
      <div class="card-header text-white" style=background-color:dodgerblue;>
<legend>Create A Free Suppliers Account.</legend>
</div>
<div class="col-sm-6">
<form method="POST" action="">
{%csrf_token%}
{{form|crispy}}
<div class="sup" align=center>
<button class="btn btn-primary text-white col-sm-6 m-2">Sign Up</button>
</div>
  </form>
  </div>
  </div>
  </div>
  </div>
{%endblock%}