Supply/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('business.urls')),
    path('chat/',include('chat.urls'))
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views
from accounts.views import SupplierSignupView,CustomerSignupView
app_name="accounts"
urlpatterns=[
path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
path('logout/',auth_views.LogoutView.as_view(template_name='accounts/logout.html'),name="logout"),
path('supplier/',SupplierSignupView.as_view(),name="supplier"),
path('customer/',CustomerSignupView.as_view(),name="customer"),
path('SupplierProfile/',views.SupplierProfileView,name="profile"),
path('CustomerProfile/',views.CustomerProfileView,name="profilecus"),
]

business/urls.py
from django.urls import path
from business import views
app_name="business"

urlpatterns=[
path('',views.WelcomeView,name="welcome"),
path('home/',views.HomeView,name='home'),
path('product/<id>/details/',views.ProductView,name="details"),
path('update/product/<id>/',views.UpdateView,name='update'),
path('delete/product/<id>/',views.ProductDelete,name='delete'),
path('addProduct/',views.AddProductView,name="addProduct"),
path('supplier/<id>/details/',views.SupplierDetailsView,name="supplierdetails"),
path('counties/',views.CountyView,name='county'),
path('supply/',views.SupplierData,name="supply"),
path('supplier/details/<id>/',views.SpecificSupplier,name="supplierlocation")
]

chat/urls.py
from django.urls import path
from chat import views
from django.contrib.auth import views as auth_views
app_name="chat"


urlpatterns=[
path('',views.index,name='index'),
path('<room_name>/',views.room,name="room"),
]

business/models.py
from django.db import models
from accounts.models import User,Categories


class Products(models.Model):
    item=models.CharField(max_length=50)
    category=models.ForeignKey(Categories,on_delete=models.CASCADE)
    price=models.IntegerField(default=0)
    discount_price=models.IntegerField(blank=True,null=True)
    description=models.TextField(blank=True,null=True)
    image=models.ImageField(upload_to=f'Products')
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    date_added=models.DateField(auto_now_add=True)
    date_updated=models.DateField(auto_now=True)


    def __str__(self):
        return self.item

business/forms.py
from django.forms import ModelForm
from django import forms
from business.models import Products

class UpdateForm(ModelForm):
    class Meta:
        model=Products
        fields=['item','category','price','discount_price','image','description']

business/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from accounts.decorators import supplier_required,customer_required
from django.contrib.auth.decorators import login_required
from business.models import Products
from business.forms import UpdateForm
from accounts.models import Supplier,Counties
from django.core.serializers import serialize

def WelcomeView(request):
    context={

    }
    return render(request,'business/welcome.html',context)
@login_required
def HomeView(request):
    product=Products.objects.filter(user=request.user)
    supplier=Supplier.objects.all()
    context={
    'product':product,
    'supplier':supplier
    }
    return render(request,'business/home.html',context)
@login_required
@supplier_required
def ProductView(request,id):
    productdetails=Products.objects.get(user=request.user,id=id)
    context={
    'productdetails':productdetails
    }
    return render(request,'business/details.html',context)
@login_required
@supplier_required
def UpdateView(request,id):
    productUpdate=Products.objects.get(user=request.user,id=id)
    form=UpdateForm(instance=productUpdate)
    if request.method=="POST":
        form=UpdateForm(request.POST or None,request.FILES or None, instance=productUpdate)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(f'/product/{id}/details/')
    context={
    'form':form
    }
    return render(request,'business/update.html',context)
@login_required
@supplier_required
def ProductDelete(request,id):
    deleteProduct=Products.objects.get(user=request.user,id=id)
    deleteProduct.delete()
    return HttpResponseRedirect('/home/')
@login_required
@supplier_required
def AddProductView(request):
    if request.method=="POST":
        form=UpdateForm(request.POST or None,request.FILES or None)
        if form.is_valid():
            product=form.save(commit=False)
            product.user=request.user
            product.save()
            return HttpResponseRedirect('/home/')
    else:
        form=UpdateForm()
    context={
    'form':form
    }
    return render(request,'business/addProduct.html',context)
def SupplierDetailsView(request,id):
    supObj=Supplier.objects.get(id=id)
    context={
    'supObj':supObj
    }

    return render(request,'business/supplierdetails.html',context)


#========================================================================
def CountyView(request):
    counties=serialize('geojson',Counties.objects.all())
    return HttpResponse(counties,content_type='json')
def SupplierData(request):
    supply=serialize('geojson',Supplier.objects.all())
    return HttpResponse(supply,content_type='json')
def SpecificSupplier(request,id):
    print(id)
    sup=serialize('geojson',Supplier.objects.filter(id=id))
    return HttpResponse(sup,content_type="json")

business/templates/business/addProduct.html
{%extends 'accounts/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="container" align=center>
  <div class="col-sm-8" align=left>
  <div class="card text-white" style=background-color:#44505e;>
    <div class="card-header" style=background-color:dodgerblue;>
      <legend>Add Products</legend>
      </div>
      <div class="body m-4">
<form method="POST" action="" enctype="multipart/form-data">
{%csrf_token%}
{{form|crispy}}
<div class="mybtn" align=center>
<button class="btn btn-primary col-sm-5">Add Product</button>
</div>
  </form>
  </div>
  </div>
  </div>
  </div>

{%endblock%}

business/templates/business/details.html
{%extends 'accounts/base.html'%}
{%block content%}
<div class="container">
<div class="card card-fluid shadow-lg">
  <div class="row">
  <div class="col-sm-5">
    <img src="{{productdetails.image.url}}" class="img-fluid p-1" height="180" alt="edit">
    </div>
    <div class="col-sm-7">
      <div class="item" style=color:#55b000;>
      <legend>{{productdetails.item}}</legend>
      </div>
      <div class="description" style=color:#55b000;>
        {{productdetails.description}}
        </div>
          <div class="date"style=color:#55b000;>
            <div class="row m-1">
              <b class="text-muted">Date Added:- </b>{{productdetails.date_updated}}
              </div>
            </div>
            <hr>
            <div class="price" style=color:#55b000;>
              <h4>Ksh {{productdetails.price}}</h4>
              </div>
      <div class="row" align=center>
        <div class="col-sm-6">
        <div class="update m-1">
          <a href="{%url 'business:update' productdetails.id%}"><button class="btn text-white col-sm-6 p-1" style=background-color:#3038ed;><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Update</button></a>
          </div>
          </div>
        <div class="col-sm-6">
      <div class="delete m-1">
        <a href="{%url 'business:delete' productdetails.id%}"><button class="btn text-white col-sm-6 p-1" style=background-color:#d54936;><i class="fa fa-trash" aria-hidden="true"></i> Delete</button></a>
        </div>
        </div>
          </div>
          <hr>
      </div>
      </div>
  </div>

  </div>
  style=color:#2d188d;

{%endblock%}

business/templates/business/home.html
{%extends 'accounts/base.html'%}
{%load static%}
{%load leaflet_tags%}
{%load geojson_tags%}
{%block content%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
{% leaflet_js%}
{% leaflet_css%}

{%if user.is_supplier and user.is_authenticated%}
<div class="jumbotron shadow-lg">
  <div class="row">
    Welcome {{user.username}},
<div class="container">
    <div class="addbutton" align=left>
      <a href="{%url 'business:addProduct'%}"><button class="btn text-white " style=background-color:#9232d3;><i class="fa fa-plus"></i> Add Products</button></a>
      </div>
  <div class="row" align=center>
  {%for product in product%}
<div class="card m-2" style=background-color:#f68b1e; align=center>
  <img src="{{product.image.url}}" height="200" width="180" alt="edit">
  <a href="{%url 'business:details' product.id%}">
    <div class="card m-1">
  <div class="item">
  {{product.item}}
  </div>
  <div class="price">
  <b>Ksh.{{product.price}}</b>
  </div>
  </div>
  </a>
  </div>
  {%endfor%}
  </div>
  </div>
  </div>
  </div>

  {%elif user.is_customer and user.is_authenticated%}
  <div class="container-fluid">
    <div class="row">
    <div class="col-sm-3 shadow-lg" style=height:43rem;background-color:#2c3e50;>
    <div id="search">
    <a id="room-name-input"><i class="fa fa-envelope fa-lg float-right m-2" id="room-name-submit" style=color:lavender;></i></a>
      <!--<p class="text-white" id="room-name-input"><button class="btn" id="room-name-submit">group</button></p>-->

      <script>
          document.querySelector('#room-name-input').focus();
          document.querySelector('#room-name-input').onkeyup = function(e) {
              if (e.keyCode === 13) {  // enter, return
                  document.querySelector('#room-name-submit').click();
              }
          };

          document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName='group';
              window.location.pathname = '/chat/' + roomName + '/';
          };
      </script>


      <form class="form-inline m-2">
        <i class="fa fa-search text-white btn" aria-hidden="true"></i>
        <input class="form-control form-control-sm ml-1 w-75" type="text" placeholder="Search" aria-label="Search">
      </form>
    </div>
    <div id="contacts">
      <ul>
        {%for supplier in supplier%}
          <div class="wraper">
            <a href="{%url 'business:supplierdetails' supplier.id%}"><img src="{{supplier.image.url}}" class="rounded-circle m-1" width="70" height='70' alt="edit"></a>
            <div class="meta">
              <a href="{%url 'business:supplierdetails' supplier.id%}"><p class="name ml-2 text-white">{{supplier.user.username}}</p></a>
            </div>
          </div>
          {%endfor%}
      </ul>
    </div>
    </div>
    <div class="col-sm-9 shadow-lg bg-white">
      <style type="text/css">
        #gis {width:100%;height:620px;
        }
        </style>
        <script type="text/javascript" src="{% static 'leaflet.ajax.js' %}" ></script>

	<link rel="stylesheet" type="text/css" href="{% static 'leaflet.groupedlayercontrol.css' %}">
	<script type="text/javascript" src="{% static 'leaflet.groupedlayercontrol.js' %}" ></script>

  <script type="text/javascript" src="{% static 'leaflet-routing-machine.js' %}" ></script>
  	<link rel="stylesheet" type="text/css" href="{% static 'leaflet-routing-machine.css' %}">

    <script type="text/javascript" src="{% static 'easy-button.js' %}" ></script>
    	<link rel="stylesheet" type="text/css" href="{% static 'easy-button.css' %}">
<h1>Map</h1>
<script type="text/javascript">
function our_layers(map,options){
  var osm = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
				maxZoom: 19,
				attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
			});
    var OpenTopoMap = L.tileLayer('http://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', {
			maxZoom: 17,
			attribution: 'Map data: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)'
		});
  var datasets=new L.GeoJSON.AJAX("{%url 'business:county'%}",{
    style: function colors(feature){
    switch(feature.properties.name){
      case 'WAJIR':
        return{
          color: 'orange',
          fillOpacity: 0.8
        };
      break;
      case 'ISIOLO':
        return{
          color: 'purple',
          fillOpacity: 0.8
        };
      break;

    }
  },
    onEachFeature: function(feature,layer){
      layer.bindPopup(feature.properties.name.toString())
    }
  });
  var points=new L.GeoJSON.AJAX("{%url 'business:supply'%}",{

    onEachFeature:function(feature,layer){
      layer.bindPopup(feature.properties.telephone.toString())
    }
  });
  datasets.addTo(map);
  points.addTo(map);

  var baseLayers = {
    "OSM": osm,
  }

  var groupedOverlays = {
    "Layers": {
      "Counties": datasets,
      "Suppliers": points
    }

  };
  L.control.groupedLayers(baseLayers, groupedOverlays).addTo(map);

L.easyButton('fa-compass',
  function (){
    $('.leaflet-routing-container').is(':visible') ? routing.removeFrom(map) : routing.addTo(map)
  },
  'Routing'
).addTo(map);


function createButton(label, container) {
    var btn = L.DomUtil.create('button', '', container);
    btn.setAttribute('type', 'button');
    btn.innerHTML = label;
    return btn;
}
}

  </script>
{%leaflet_map 'gis' callback='window.our_layers'%}
</div>
  {%else%}
<a href="{%url 'account:login'%}"><button class="btn text-white " style=background-color:#9232d3;>Login</button></a>
  {%endif%}
{%endblock%}

business/templates/business/supplierdetails.html
{%extends 'accounts/base.html'%}
{%load static%}
{%load leaflet_tags%}
{%block content%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
{%leaflet_js%}
{%leaflet_css%}
<div class="container-fluid">
  <div class="row">
  <div class="col-sm-3 shadow-lg" style=height:43rem;background-color:#2c3e50;>
  <div id="search"  style=background-color#2c3e50;>
    <form class="form-inline m-2">
      <i class="fa fa-search text-white btn" aria-hidden="true"></i>
      <input class="form-control form-control-sm ml-1 w-75" type="text" placeholder="Search" aria-label="Search">
    </form>
  </div>
  <div id="suppliers">
    <ul>
        <div class="wraper">
          <a href=""><img src="{{supObj.image.url}}" class="rounded-circle m-1" width="70" height='70' alt="edit"></a>
          <div class="meta">
            <a href=""><p class="name ml-2 text-white">{{supObj.user.username}} {{supObj.telephone}}</p></a>

          </div>
        </div>
    </ul>
  </div>
  </div>
  <div class="col-sm-9 shadow-lg bg-white">
    <style type="text/css">
      #gis {width:100%;height:580px;}
      </style>
      <script type="text/javascript" src="{% static 'leaflet.ajax.js' %}" ></script>

<link rel="stylesheet" type="text/css" href="{% static 'leaflet.groupedlayercontrol.css' %}">
<script type="text/javascript" src="{% static 'leaflet.groupedlayercontrol.js' %}" ></script>

<script type="text/javascript" src="{% static 'leaflet-routing-machine.js' %}" ></script>
  <link rel="stylesheet" type="text/css" href="{% static 'leaflet-routing-machine.css' %}">

  <script type="text/javascript" src="{% static 'easy-button.js' %}" ></script>
    <link rel="stylesheet" type="text/css" href="{% static 'easy-button.css' %}">
    <script type="text/javascript">
      function my_layer(map,options){
        var osm = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
              maxZoom: 19,
              attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
            });
            var OpenTopoMap = L.tileLayer('http://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', {
        			maxZoom: 17,
        			attribution: 'Map data: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)'
        		});
        var datasets=new L.GeoJSON.AJAX("{%url 'business:county'%}",{
          style: function colors(feature){
  switch(feature.properties.name){
    case 'WAJIR':
    return{
        color: 'black',
        fillOpacity: 0.8
      };
      break;
      case 'ISIOLO':
      return{
        color: 'purple',
        fillOpacity: 0.8
      };
      break;
    }
  },
          onEachFeature: function(feature,layer){
            layer.bindPopup(feature.properties.name.toString())
          }
        });
        var points=new L.GeoJSON.AJAX("{%url 'business:supplierlocation' supObj.id%}",{
          onEachFeature:function(feature,layer){
            layer.bindPopup(feature.properties.user.toString())
          }
        });
        datasets.addTo(map);
        points.addTo(map);

        var baseLayers = {
          "OSM": osm,
        }

        var groupedOverlays = {
          "Layers": {
            "Counties": datasets,
            "Supplier": points
          }

        };
        L.control.groupedLayers(baseLayers, groupedOverlays).addTo(map);

        var routing =  L.Routing.control({
          waypoints: [
            L.latLng(0.23, 40.64),
            L.latLng(0.23, 34.64)
          ]
        }).addTo(map);

        L.easyButton('fa-compass',
          function (){
            $('.leaflet-routing-container').is(':visible') ? routing.removeFrom(map) : routing.addTo(map)
          },
          'Routing'
        ).addTo(map);


        function createButton(label, container) {
            var btn = L.DomUtil.create('button', '', container);
            btn.setAttribute('type', 'button');
            btn.innerHTML = label;
            return btn;
        }
      }
      </script>
{%leaflet_map 'gis' callback="window.my_layer"%}
<h1>Products</h1>
  </div>
    </div>
    </div>

{%endblock%}

business/templates/business/update.html
{%extends 'accounts/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="container" align=center>
  <div class="col-sm-8" align=left>
  <div class="card text-white" style=background-color:#44505e;>
    <div class="card-header" style=background-color:dodgerblue;>
      <legend>Update Product</legend>
      </div>
      <div class="body m-4">
<form method="POST" action="" enctype="multipart/form-data">
{%csrf_token%}
{{form|crispy}}
<div class="mybtn" align=center>
<button class="btn btn-primary col-sm-5">Update Product</button>
</div>
  </form>
  </div>
  </div>
  </div>
  </div>
{%endblock%}

business/templates/business/welcome.html
{%extends 'accounts/base.html'%}
{%block content%}

hello from welcome page

{%endblock%}